/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/sheet`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/projectCard`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/ProjectCard`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/ProjectForm`; params?: Router.UnknownInputParams; } | { pathname: `/projects/[id]`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/sheet`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/projectCard`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/ProjectCard`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/ProjectForm`; params?: Router.UnknownOutputParams; } | { pathname: `/projects/[id]`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/sheet${`?${string}` | `#${string}` | ''}` | `/../components/ui/projectCard${`?${string}` | `#${string}` | ''}` | `/../components/ui/ProjectCard${`?${string}` | `#${string}` | ''}` | `/../components/ui/ProjectForm${`?${string}` | `#${string}` | ''}` | `/projects/[id]${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/sheet`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/projectCard`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/ProjectCard`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/ProjectForm`; params?: Router.UnknownInputParams; } | { pathname: `/projects/[id]`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
